/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantnatys;

/**
 *
 * @author USUARIO
 */ 
import javax.swing.JOptionPane;


public class VentanPedido extends javax.swing.JFrame {

    private Cliente cliente;
    private Menu menu;
    private Cocina cocina;
    private Pedido pedidoActual;
    /**
     * Creates new form VentanPedido
     */
    public VentanPedido() {
        initComponents();
          
        setLocationRelativeTo(null); // centramos la ventana
        setTitle("Registro de Cliente y Pedido - Restaurant Naty's");
        
        //usar menu y cocina
        menu = RestaurantNatys.menu;
        cocina = RestaurantNatys.cocina;
        
        //Cantidad del pedido
        SpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        //Hacer invisible al inicio
        ComboSabor.setVisible(false);        
        lblSabor.setVisible(false);


        //Lenar ComboBox con menu
        ComboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Hamburguesa Clasica (Carne de res, Pan, Queso)",
            "Perro Caliente",
            "Papas Fritas (Papas a la francesa)",
            "Gaseosa ← (Seleccione y elija sabor)",
            "Nuggets de Pollo (Pollo fresco)"
        }));
        
        ComboSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        "Cola",
        "Naranja",
        "Manzana"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Documento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        Producto = new javax.swing.JLabel();
        ComboProducto = new javax.swing.JComboBox<>();
        btnRegistrarCliente = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        SpinnerCantidad = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        ComboSabor = new javax.swing.JComboBox<>();
        lblSabor = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        panelDSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDIzquierdo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Naty's");
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 245, 228));

        Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(153, 0, 0));
        Nombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        Documento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Documento.setForeground(new java.awt.Color(153, 0, 0));
        Documento.setText("Documento");

        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        Producto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Producto.setForeground(new java.awt.Color(153, 0, 0));
        Producto.setText("Producto");

        ComboProducto.setBackground(new java.awt.Color(153, 0, 51));
        ComboProducto.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        ComboProducto.setForeground(new java.awt.Color(255, 255, 255));
        ComboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" }));
        ComboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProductoActionPerformed(evt);
            }
        });

        btnRegistrarCliente.setBackground(new java.awt.Color(153, 0, 0));
        btnRegistrarCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        btnRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnPedido.setBackground(new java.awt.Color(153, 0, 0));
        btnPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnPedido.setText("Agregar al pedido");
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/restaurantnatys/logo (1).png"))); // NOI18N

        SpinnerCantidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Cantidad");

        BtnSalir.setBackground(new java.awt.Color(153, 0, 51));
        BtnSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        ComboSabor.setBackground(new java.awt.Color(153, 0, 51));
        ComboSabor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ComboSabor.setForeground(new java.awt.Color(255, 255, 255));
        ComboSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSabor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSabor.setForeground(new java.awt.Color(153, 0, 0));
        lblSabor.setText("Sabores");

        btnFinalizar.setBackground(new java.awt.Color(153, 0, 0));
        btnFinalizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar y cobrar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        panelDSuperior.setBackground(new java.awt.Color(139, 69, 19));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESTAURANT NATY'S");

        javax.swing.GroupLayout panelDSuperiorLayout = new javax.swing.GroupLayout(panelDSuperior);
        panelDSuperior.setLayout(panelDSuperiorLayout);
        panelDSuperiorLayout.setHorizontalGroup(
            panelDSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDSuperiorLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDSuperiorLayout.setVerticalGroup(
            panelDSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDSuperiorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelDIzquierdo.setBackground(new java.awt.Color(139, 69, 19));

        javax.swing.GroupLayout panelDIzquierdoLayout = new javax.swing.GroupLayout(panelDIzquierdo);
        panelDIzquierdo.setLayout(panelDIzquierdoLayout);
        panelDIzquierdoLayout.setHorizontalGroup(
            panelDIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelDIzquierdoLayout.setVerticalGroup(
            panelDIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(139, 69, 19));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Realice su pedido");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Registrarse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelDIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboSabor, 0, 172, Short.MAX_VALUE)
                            .addComponent(Producto, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFoto)
                                .addGap(65, 65, 65))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnSalir)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnPedido)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFinalizar)))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelDSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Documento))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Producto)
                                .addGap(18, 18, 18)
                                .addComponent(ComboSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFoto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSabor)
                        .addGap(18, 18, 18)
                        .addComponent(ComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(BtnSalir)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        String documento = txtDocumento.getText().trim();

        // Validar que los campos no estén vacíos
        if (nombre.isEmpty() || documento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", 
                "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que el documento tenga 10 numeros
        if (!documento.matches("\\d{10}")) {  // \d{10} = exactamente 10 números
            JOptionPane.showMessageDialog(this, 
                "El documento debe tener EXACTAMENTE 10 dígitos numéricos.\n" +
                "Ejemplo correcto: 1234567890", 
                "Documento inválido", JOptionPane.ERROR_MESSAGE);

            txtDocumento.requestFocus();   // Pone el cursor de nuevo en el campo
            txtDocumento.selectAll();      // Selecciona todo 
            return;
        }

        //Mnesaje de registro
        cliente = new Cliente(nombre, documento);
        JOptionPane.showMessageDialog(this, 
            "Cliente registrado correctamente:\n" +
            nombre + " - " + documento, 
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Desabilitar boton
        btnRegistrarCliente.setEnabled(false);
        btnRegistrarCliente.setText("Cliente Registrado");
    

    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void ComboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProductoActionPerformed
        // TODO add your handling code here:                                           
           String seleccionado = ComboProducto.getSelectedItem().toString();

    // Mostrar/ocultar sabores para gaseosa
    if (seleccionado.toLowerCase().contains("gaseosa")) {
        lblSabor.setVisible(true);
        ComboSabor.setVisible(true);
    } else {
        lblSabor.setVisible(false);
        ComboSabor.setVisible(false);
    }

    // CAMBIAR LA IMAGEN SEGÚN EL PRODUCTO SELECCIONADO
    String rutaImagen = "/com/mycompany/restaurantnatys/";
    
    if (seleccionado.contains("Hamburguesa")) {
        rutaImagen += "hamburguesa.png";
    } else if (seleccionado.contains("Perro Caliente")) {
        rutaImagen += "perro.png";
    } else if (seleccionado.contains("Papas Fritas")) {
        rutaImagen += "papas.png";
    } else if (seleccionado.contains("Gaseosa")) {
        rutaImagen += "gaseosa.png";
    } else if (seleccionado.contains("Nuggets")) {
        rutaImagen += "nuggets.png";
    } else {
        rutaImagen += "foto.png"; // imagen por defecto
    }

    // Aplicar la nueva imagen
    lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource(rutaImagen)));
    }//GEN-LAST:event_ComboProductoActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        // TODO add your handling code here:
        // Verificar que el cliente ya esté registrado
                                          
        if (cliente == null) {
        JOptionPane.showMessageDialog(this, "Primero registre al cliente.");
        return;
    }

        String productoTexto = ComboProducto.getSelectedItem().toString();
        int cantidad = (int) SpinnerCantidad.getValue();
        ItemPedido item = null;

        if (productoTexto.toLowerCase().contains("gaseosa")) {
            // COMBOBOX DEL DISEÑO 
            String sabor = ComboSabor.getSelectedItem().toString().toLowerCase();
            String nombreGaseosa = "Gaseosa " + sabor; 
            item = new ItemPedido(nombreGaseosa, cantidad, 4000);
        } else {
            // Producto normal
            int indice = ComboProducto.getSelectedIndex();
            ItemPedido productoDelMenu = menu.getProductos().get(indice);
            item = new ItemPedido(productoDelMenu.getNomProducto(),cantidad,productoDelMenu.getPrecioUni());       
        }

        // Crear o usar pedido actual
        if (pedidoActual == null) {
            pedidoActual = new Pedido(cliente);
        }
        pedidoActual.agregarItem(item);
        pedidoActual.calcularTotal();

        cocina.reciPedido(pedidoActual);
        // Descontar inventario 
        cocina.usarIngredientesPedido(pedidoActual, menu);
        
        /*Mesa mesa = new Mesa(1);
        Pago pago = new Pago(1, pedidoActual.getTotal(), "Efectivo");
        pago.generarFactura(pedidoActual, mesa, cliente);
        pago.guardarEnArchivo(pedidoActual, cliente);*/

        //panel de pedido
        JOptionPane.showMessageDialog(this,
            "¡PEDIDO COMPLETADO!\n\n" +
            "Producto: " + item.getNomProducto() + "\n" +
            "Cantidad: " + cantidad + "\n" +
            "Total: " + RestaurantNatys.formatoPrecio(pedidoActual.getTotal()),
            "¡Gracias por su pedido!",
            JOptionPane.INFORMATION_MESSAGE);

        // Reiniciar campos
        ComboProducto.setSelectedIndex(0);
        SpinnerCantidad.setValue(1);
        lblSabor.setVisible(false);
        ComboSabor.setVisible(false);
        
        
    
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        //panel de salida
        int opcion = JOptionPane.showConfirmDialog(this, 
        "¿Seguro que desea salir?\n¡Gracias por visitar Restaurant Naty's! ", 
        "¡Hasta pronto!", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.INFORMATION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            new VentanaInicio().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        if (cliente == null || pedidoActual == null || pedidoActual.getListaItems().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay pedido para cobrar.");
        return;
        }

        // Generar UNA SOLA factura
        Mesa mesa = new Mesa(1);
        Pago pago = new Pago(1, pedidoActual.getTotal(), "Efectivo");
        pago.generarFactura(pedidoActual, mesa, cliente);
        pago.guardarEnArchivo(pedidoActual, cliente);

        // ¡GUARDAR EL PEDIDO PARA EL REPORTE DEL DÍA!
        RestaurantNatys.pedidosDelDia.add(pedidoActual);

        JOptionPane.showMessageDialog(this,
            "¡COBRO COMPLETADO!\n" +
            "Cliente: " + cliente.getNombre() + "\n" +
            "Total cobrado: " + RestaurantNatys.formatoPrecio(pedidoActual.getTotal()),
            "Factura Final Generada", JOptionPane.INFORMATION_MESSAGE);

        // Reiniciar para el próximo cliente
        cliente = null;
        pedidoActual = null;
        btnRegistrarCliente.setEnabled(true);
        btnRegistrarCliente.setText("Registrar Cliente");
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> ComboProducto;
    private javax.swing.JComboBox<String> ComboSabor;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Producto;
    private javax.swing.JSpinner SpinnerCantidad;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblSabor;
    private javax.swing.JPanel panelDIzquierdo;
    private javax.swing.JPanel panelDSuperior;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
