/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantnatys;

/**
 *
 * @author USUARIO
 */ 
import javax.swing.JOptionPane;


public class VentanPedido extends javax.swing.JFrame {

    private Cliente cliente;
    private Menu menu;
    private Cocina cocina;
    private Pedido pedidoActual;
    /**
     * Creates new form VentanPedido
     */
    public VentanPedido() {
        initComponents();
         
        setLocationRelativeTo(null); // centramos la ventana
        setTitle("Registro de Cliente y Pedido - Restaurant Naty's");
        
        menu = new Menu();
        cocina= new Cocina();
        cocina.inicializarInventarioDesdeMenu(menu);
        
        //Cantidad del pedido
        SpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        //Hacer invisible al inicio
        ComboSabor.setVisible(false);        
        lblSabor.setVisible(false);


        //Lenar ComboBox con menu
        ComboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Hamburguesa Clasica (Carne de res, Pan, Queso)",
            "Perro Caliente",
            "Papas Fritas (Papas criollas)",
            "Gaseosa ← (Seleccione y elija sabor)",
            "Nuggets de Pollo (Pollo fresco)"
        }));
        
        ComboSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        "Cola",
        "Naranja",
        "Manzana"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Documento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        Producto = new javax.swing.JLabel();
        ComboProducto = new javax.swing.JComboBox<>();
        btnRegistrarCliente = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SpinnerCantidad = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        ComboSabor = new javax.swing.JComboBox<>();
        lblSabor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Naty's");
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(153, 0, 0));
        Nombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        Documento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Documento.setForeground(new java.awt.Color(153, 0, 0));
        Documento.setText("Documento");

        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        Producto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Producto.setForeground(new java.awt.Color(153, 0, 0));
        Producto.setText("Producto");

        ComboProducto.setBackground(new java.awt.Color(255, 153, 153));
        ComboProducto.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        ComboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" }));
        ComboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProductoActionPerformed(evt);
            }
        });

        btnRegistrarCliente.setBackground(new java.awt.Color(255, 153, 153));
        btnRegistrarCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnPedido.setBackground(new java.awt.Color(255, 153, 153));
        btnPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPedido.setText("Hacer Pedido");
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/restaurantnatys/foto.png"))); // NOI18N

        SpinnerCantidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Cantidad");

        BtnSalir.setBackground(new java.awt.Color(255, 153, 153));
        BtnSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        ComboSabor.setBackground(new java.awt.Color(255, 153, 153));
        ComboSabor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ComboSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSabor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSabor.setForeground(new java.awt.Color(153, 0, 0));
        lblSabor.setText("Sabores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnRegistrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btnPedido)
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(BtnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboProducto, 0, 172, Short.MAX_VALUE)
                            .addComponent(Producto, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(lblSabor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboSabor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Documento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Producto)
                        .addGap(18, 18, 18)
                        .addComponent(ComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblSabor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarCliente)
                            .addComponent(btnPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSalir)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        String documento = txtDocumento.getText().trim();

        //Verificar campo
        if (nombre.isEmpty() || documento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
            return;
        }

        cliente = new Cliente(nombre, documento);
        JOptionPane.showMessageDialog(this, "Cliente registrado correctamente.");


    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void ComboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProductoActionPerformed
        // TODO add your handling code here:                                           
    String seleccionado = ComboProducto.getSelectedItem().toString();
    
        //Muestra el sabor
        if (seleccionado.toLowerCase().contains("gaseosa")) {
            lblSabor.setVisible(true);      // Muestra el JLabel "Sabor:"
            ComboSabor.setVisible(true);     
        } else {
            lblSabor.setVisible(false);      // Oculta si es otro producto
            ComboSabor.setVisible(false);
        }
    }//GEN-LAST:event_ComboProductoActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        // TODO add your handling code here:
        // Verificar que el cliente ya esté registrado
                                          
        if (cliente == null) {
        JOptionPane.showMessageDialog(this, "Primero registre al cliente.");
        return;
    }

        String productoTexto = ComboProducto.getSelectedItem().toString();
        int cantidad = (int) SpinnerCantidad.getValue();
        ItemPedido item = null;

        if (productoTexto.toLowerCase().contains("gaseosa")) {
            // COMBOBOX DEL DISEÑO 
            String sabor = ComboSabor.getSelectedItem().toString().toLowerCase();
            String nombreGaseosa = "Gaseosa " + sabor; 
            item = new ItemPedido(nombreGaseosa, cantidad, 4000);
        } else {
            // Producto normal
            int indice = ComboProducto.getSelectedIndex();
            ItemPedido base = menu.getProductos().get(indice);
            item = new ItemPedido(base.getNomProducto(), cantidad, base.getPrecioUni());
        }

        // Crear o usar pedido actual
        if (pedidoActual == null) {
            pedidoActual = new Pedido(cliente);
        }
        pedidoActual.agregarItem(item);
        pedidoActual.calcularTotal();

        cocina.reciPedido(pedidoActual);
        cocina.marPedList(pedidoActual.getIdPedido(), menu);

        Mesa mesa = new Mesa(1);
        Pago pago = new Pago(1, pedidoActual.getTotal(), "Efectivo");
        pago.generarFactura(pedidoActual, mesa, cliente);
        pago.guardarEnArchivo(pedidoActual, cliente);

        JOptionPane.showMessageDialog(this,
            "¡PEDIDO COMPLETADO!\n\n" +
            "Producto: " + item.getNomProducto() + "\n" +
            "Cantidad: " + cantidad + "\n" +
            "Total: " + RestaurantNatys.formatoPrecio(pedidoActual.getTotal()),
            "¡Gracias por su pedido!",
            JOptionPane.INFORMATION_MESSAGE);

        // Reiniciar campos
        ComboProducto.setSelectedIndex(0);
        SpinnerCantidad.setValue(1);
        lblSabor.setVisible(false);
        ComboSabor.setVisible(false);
    
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, 
        "¿Seguro que desea salir?\n¡Gracias por visitar Restaurant Naty's! ", 
        "¡Hasta pronto!", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.INFORMATION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            new VentanaInicio().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> ComboProducto;
    private javax.swing.JComboBox<String> ComboSabor;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Producto;
    private javax.swing.JSpinner SpinnerCantidad;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblSabor;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
